#### Numpy tricks (useful numpy functions)

In [37]:
import numpy as np

a = np.random.randint(1,100,6).reshape(2,3)

In [38]:
b = np.append(a, np.ones((a.shape[0],1)), axis=1)
b

array([[ 9., 83., 46.,  1.],
       [90., 15., 21.,  1.]])

In [39]:
c = np.random.randint(1,10,8).reshape(b.shape)
c

array([[9, 8, 7, 5],
       [7, 3, 7, 9]])

In [40]:
#alternative to hstack and vstack
d = np.concatenate((b,c), axis=0)
d

array([[ 9., 83., 46.,  1.],
       [90., 15., 21.,  1.],
       [ 9.,  8.,  7.,  5.],
       [ 7.,  3.,  7.,  9.]])

In [41]:
np.unique(d)

array([ 1.,  3.,  5.,  7.,  8.,  9., 15., 21., 46., 83., 90.])

In [ ]:
#to change to a higher dim
d.shape, np.expand_dims(d, axis=0).shape

((4, 4), (1, 4, 4))

In [49]:
np.where(d>20),d[np.where(d>20)],d[d>20]

((array([0, 0, 1, 1]), array([1, 2, 0, 2])),
 array([83., 46., 90., 21.]),
 array([83., 46., 90., 21.]))

In [ ]:
#np.where() different than bool masking: d[d>20] (bool masking does not provide the indices)
rows, cols = np.where(d>20) #NOTE: here d is 2D

print(d)
for i,j in zip(rows, cols):
    print(f'arr[{i}][{j}] = ', d[i][j])

(array([0, 0, 1, 1]), array([1, 2, 0, 2]))
[[ 9. 83. 46.  1.]
 [90. 15. 21.  1.]
 [ 9.  8.  7.  5.]
 [ 7.  3.  7.  9.]]
arr[0][1] =  83.0
arr[0][2] =  46.0
arr[1][0] =  90.0
arr[1][2] =  21.0
[83. 46. 90. 21.]


In [55]:
#np.where(condition, if-true, if-false)
print(b)
print(c)
np.where(b>20, 50, c) #NOTICE: we are changing in b, replacing all the false condition as c's values except where b>20 (works if b and c dimensions doesn't mismatch)

[[ 9. 83. 46.  1.]
 [90. 15. 21.  1.]]
[[9 8 7 5]
 [7 3 7 9]]


array([[ 9, 50, 50,  5],
       [50,  3, 50,  9]])

In [ ]:
#np.argmax() and np.argmin()- returns the index where the max and min value is
d, np.argmax(d), np.argmax(d, axis=0)

(array([[ 9., 83., 46.,  1.],
        [90., 15., 21.,  1.],
        [ 9.,  8.,  7.,  5.],
        [ 7.,  3.,  7.,  9.]]),
 np.int64(4),
 array([1, 0, 0, 3]))

In [63]:
#np.cumsum() and np.prod() - gives the cummulative sum and product
np.cumsum(d, axis=0), np.cumprod(d, axis=1), np.cumsum(d) #converted to 1d first

(array([[  9.,  83.,  46.,   1.],
        [ 99.,  98.,  67.,   2.],
        [108., 106.,  74.,   7.],
        [115., 109.,  81.,  16.]]),
 array([[9.0000e+00, 7.4700e+02, 3.4362e+04, 3.4362e+04],
        [9.0000e+01, 1.3500e+03, 2.8350e+04, 2.8350e+04],
        [9.0000e+00, 7.2000e+01, 5.0400e+02, 2.5200e+03],
        [7.0000e+00, 2.1000e+01, 1.4700e+02, 1.3230e+03]]),
 array([  9.,  92., 138., 139., 229., 244., 265., 266., 275., 283., 290.,
        295., 302., 305., 312., 321.]))

In [65]:
#percentile
np.percentile(d, 50),np.median(d) == np.percentile(d,50), np.percentile(d, 0), np.percentile(d,100) # 100 percentile is the max, 0 percentile is the min

(np.float64(8.5), np.True_, np.float64(1.0), np.float64(90.0))

In [67]:
#histogram
a = np.random.randint(1,100, 25)
np.histogram(a, bins=[0,20,40,60,80,100])

(array([8, 5, 4, 5, 3]), array([  0,  20,  40,  60,  80, 100]))

In [74]:
#correlation coeff
salary = np.array([10000,20000,30000,40000])
exp = np.array([1,3,2,6])

np.corrcoef(salary,exp)

array([[1.        , 0.83666003],
       [0.83666003, 1.        ]])

In [85]:
#search for multiple items
items = [7, 10,20,30,40,50,60,70,80,90,100]

d, np.isin(d,items), np.where(np.isin(d,items)), d[np.where(np.isin(d,items))], d[np.isin(d,items)]

(array([[ 9., 83., 46.,  1.],
        [90., 15., 21.,  1.],
        [ 9.,  8.,  7.,  5.],
        [ 7.,  3.,  7.,  9.]]),
 array([[False, False, False, False],
        [ True, False, False, False],
        [False, False,  True, False],
        [ True, False,  True, False]]),
 (array([1, 2, 3, 3]), array([0, 2, 0, 2])),
 array([90.,  7.,  7.,  7.]),
 array([90.,  7.,  7.,  7.]))

In [96]:
#flip
d, np.flip(d), d[::-1,::-1], np.flip(d) == d[::-1,::-1], np.flip(d, axis=0), np.flip(d,axis=0) == d[::-1]

(array([[ 9., 83., 46.,  1.],
        [90., 15., 21.,  1.],
        [ 9.,  8.,  7.,  5.],
        [ 7.,  3.,  7.,  9.]]),
 array([[ 9.,  7.,  3.,  7.],
        [ 5.,  7.,  8.,  9.],
        [ 1., 21., 15., 90.],
        [ 1., 46., 83.,  9.]]),
 array([[ 9.,  7.,  3.,  7.],
        [ 5.,  7.,  8.,  9.],
        [ 1., 21., 15., 90.],
        [ 1., 46., 83.,  9.]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 array([[ 7.,  3.,  7.,  9.],
        [ 9.,  8.,  7.,  5.],
        [90., 15., 21.,  1.],
        [ 9., 83., 46.,  1.]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]))

In [104]:
#update the array values
np.put(d, [7,10],[10,20]) #NOTE: changes the original array
d

array([[10., 20., 46.,  1.],
       [90., 15., 21., 10.],
       [ 9.,  8., 20.,  5.],
       [ 7.,  3.,  7.,  9.]])

In [107]:
#delete from array
np.delete(d, [0,4,3]) #does not change the orginal array

array([20., 46., 15., 21., 10.,  9.,  8., 20.,  5.,  7.,  3.,  7.,  9.])

Set functions
- np.unique()
- np.union1d()
- np.intersect1d()
- np.setdiff1d()
- np.isin1d()
- np.setxor1d()

In [117]:
a = np.array([1,2,3,4,5])
b = np.array([3,2,4,8,0])
np.union1d(a,b), np.intersect1d(a,b), np.setdiff1d(a,b), np.isin(a,1), np.setxor1d(a,b)

(array([0, 1, 2, 3, 4, 5, 8]),
 array([2, 3, 4]),
 array([1, 5]),
 array([ True, False, False, False, False]),
 array([0, 1, 5, 8]))

In [121]:
#clip 
a = np.random.randint(1,100,15)
a, np.clip(a, a_min = 35, a_max=65) #values outside the range will be changed to a_min and a_max values

(array([91, 92, 72, 46, 90,  6, 32, 73, 71, 40, 66, 12, 12, 28,  1]),
 array([65, 65, 65, 46, 65, 35, 35, 65, 65, 40, 65, 35, 35, 35, 35]))