notes by sir: 

https://colab.research.google.com/drive/1GEkNfxnCPfzX8TCymkZJvWbkpGKZRgiK?usp=sharing#scrollTo=JAlMLFkds9KC

In [43]:
import numpy as np

a = np.array([1,2,3]) # vector
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # matrix
c = np.array([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]]) # tensor
a,b,c, a.shape, b.shape, c.shape, a.ndim, b.ndim, c.ndim

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[[1, 2],
         [3, 4]],
 
        [[1, 2],
         [3, 4]],
 
        [[1, 2],
         [3, 4]]]),
 (3,),
 (3, 3),
 (3, 2, 2),
 1,
 2,
 3)

In [80]:
#generate an empty array
np.nan * np.empty(10)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

https://www.youtube.com/watch?v=EnhgbolbEe0 (to understand the multidim array)

In [44]:
a = np.array([1,2,3], dtype=float)
b = np.array([2,3,0,-1], dtype=bool)
c = np.array([1,2,3])

a,b,c

(array([1., 2., 3.]), array([ True,  True, False,  True]), array([1, 2, 3]))

In [45]:
a = np.zeros((2,3))
b = np.ones((3,4),dtype=int)
c = np.random.random((2,4))
a,b,c

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[0.89115378, 0.23751642, 0.91917549, 0.5396565 ],
        [0.68787698, 0.24215434, 0.18970672, 0.87113208]]))

In [46]:
a = np.arange(1,10) #just like normal range() fn of python
b = np.arange(1,11,2) #start:stop:stepsize
a,b

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [ ]:
a = np.arange(1,13).reshape((1,12)) #1*12=12
b = np.arange(1,13).reshape((4,3),order='F') #4*3=12 and the orders 'C': C-like (default), 'F': Fortran-like
c = np.arange(1,13).reshape((2,6)) #2*6=12
a,b,c

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]]),
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]))

In [48]:
# copy and view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base is arr)# true (view/reference)
print(arr.reshape(2, 4) is arr)#false (copy)

True
False


In [49]:
# requires a same size for reshape
# np.arange(1,13).reshape((2,5)) #ValueError since 2*5 not equals 12

In [50]:
a = np.linspace(1,10,15) #linspace(x,y,z) = linearly spaced z points from x to y (incld. y)
b = np.linspace(1,10,15, dtype=int) #linspace(x,y,z) = linearly spaced z points from x to y (incld. y)
c = np.identity(3) #identity matrix
a,b,c

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
         4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
         7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]),
 array([ 1,  1,  2,  2,  3,  4,  4,  5,  6,  6,  7,  8,  8,  9, 10]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [51]:
a = np.arange(20).reshape(2,2,5)
print(a.ndim) #3d
print(a)
print('size: ', a.size)
print('itemsize: ', a.itemsize) #int taking 1byte/8bits on my machine

b = np.ones((2,3),dtype=bool)
print(b)
print(b.itemsize) #bool taking 1 byte on my machine

c = np.ones((2,3),dtype=float)
print(c.itemsize) #float taking 8 bytes on my machine

d = np.ones((2,3),dtype=np.int32)
print(d.itemsize) #4 bytes (4*8=32 bits) of int 

print(a.dtype, b.dtype, c.dtype, d.dtype)

3
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
size:  20
itemsize:  8
[[ True  True  True]
 [ True  True  True]]
1
8
4
int64 bool float64 int32


In [52]:
a = np.arange(8)
print(a)
print(a.dtype, a.itemsize)

a = a.astype(np.int16)
print(a)
print(a.dtype,a.itemsize)

[0 1 2 3 4 5 6 7]
int64 8
[0 1 2 3 4 5 6 7]
int16 2


### Array operations

In [53]:
a = np.arange(12,24).reshape(3,4)
b = np.arange(12).reshape(3,4)

#scalar and arithmetic opn
2*a, 2**a, 2*a == a*2, a//2, a/2, a**0.5

(array([[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]),
 array([[   4096,    8192,   16384,   32768],
        [  65536,  131072,  262144,  524288],
        [1048576, 2097152, 4194304, 8388608]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]),
 array([[ 6,  6,  7,  7],
        [ 8,  8,  9,  9],
        [10, 10, 11, 11]]),
 array([[ 6. ,  6.5,  7. ,  7.5],
        [ 8. ,  8.5,  9. ,  9.5],
        [10. , 10.5, 11. , 11.5]]),
 array([[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]))

In [54]:
#relational opn
a>20, b < 4, (a%4)==(b%2), (b+12) == a

(array([[False, False, False, False],
        [False, False, False, False],
        [False,  True,  True,  True]]),
 array([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]]),
 array([[ True,  True, False, False],
        [ True,  True, False, False],
        [ True,  True, False, False]]),
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]))

In [55]:
#arithmetic opn
a+b, a-b, a*b #its not matrix multiplication

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 array([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]),
 array([[  0,  13,  28,  45],
        [ 64,  85, 108, 133],
        [160, 189, 220, 253]]))

In [56]:
a+10

array([[22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33]])

### Arrays functions

In [57]:
a = np.random.random((3,3)).round(4)
print(a)
a = np.round(a*100)
a

[[0.8416 0.1515 0.9207]
 [0.2167 0.7046 0.3038]
 [0.6495 0.2378 0.6606]]


array([[84., 15., 92.],
       [22., 70., 30.],
       [65., 24., 66.]])

In [58]:
# max/min/sum/prod
np.sum(a),np.max(a),np.min(a), np.prod(a)

(np.float64(468.0),
 np.float64(92.0),
 np.float64(15.0),
 np.float64(551402691840000.0))

In [59]:
# 1:row 0:col
np.max(a,axis=1), np.sum(a,axis=0)

(array([92., 70., 66.]), array([171., 109., 188.]))

In [60]:
# mean/median/std/var
np.mean(a), np.mean(a, axis=0), np.median(a), np.std(a) == np.var(a)**0.5

(np.float64(52.0),
 array([57.        , 36.33333333, 62.66666667]),
 np.float64(65.0),
 np.True_)

In [61]:
#trigno
np.sin(a)

array([[ 0.73319032,  0.65028784, -0.77946607],
       [-0.00885131,  0.77389068, -0.98803162],
       [ 0.82682868, -0.90557836, -0.02655115]])

In [62]:
# dot product/matrix multiplication
a = np.arange(12).reshape((3,4))
b = np.arange(12,24).reshape((4,3))

a.dot(b), np.dot(a,b), b.dot(a), np.dot(b,a)

(array([[114, 120, 126],
        [378, 400, 422],
        [642, 680, 718]]),
 array([[114, 120, 126],
        [378, 400, 422],
        [642, 680, 718]]),
 array([[164, 203, 242, 281],
        [200, 248, 296, 344],
        [236, 293, 350, 407],
        [272, 338, 404, 470]]),
 array([[164, 203, 242, 281],
        [200, 248, 296, 344],
        [236, 293, 350, 407],
        [272, 338, 404, 470]]))

In [63]:
#log and e
a, np.log(a), np.exp(a)

/tmp/ipykernel_19810/1806384901.py:2: RuntimeWarning: divide by zero encountered in log
  a, np.log(a), np.exp(a)


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[      -inf, 0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947, 1.94591015],
        [2.07944154, 2.19722458, 2.30258509, 2.39789527]]),
 array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
        [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]]))

## Indexing and slicing

In [64]:
#chain indexing (not recommended)
a, a[0], a[2][1], a[-1][-1]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([0, 1, 2, 3]),
 np.int64(9),
 np.int64(11))

In [65]:
#multidimentional indexing(recommended, much efficient and faster than chain indexing)
a[:,3], a[1:,1:3]

(array([ 3,  7, 11]),
 array([[ 5,  6],
        [ 9, 10]]))

In [66]:
print(a[::2, ::3]) #fetch only corner elemnts
a[::2, 1::2], a[::2, ::-1], a[::-1, ::-1], a[::-1][::2,::3]


[[ 0  3]
 [ 8 11]]


(array([[ 1,  3],
        [ 9, 11]]),
 array([[ 3,  2,  1,  0],
        [11, 10,  9,  8]]),
 array([[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]]),
 array([[ 8, 11],
        [ 0,  3]]))

In [67]:
c = np.arange(27).reshape(3,3,3) 
c, c[::2][::, ::, 1], c[::2][::, 1::, 1::], c[:,1:2, 1:2], c[::2, 0, ::2], c[:,:,1]==c[::,::,1] #[blocks, rows, cols] (each element i.e, blocks, rows and cols follows start:end:stepsize)

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([[ 1,  4,  7],
        [19, 22, 25]]),
 array([[[ 4,  5],
         [ 7,  8]],
 
        [[22, 23],
         [25, 26]]]),
 array([[[ 4]],
 
        [[13]],
 
        [[22]]]),
 array([[ 0,  2],
        [18, 20]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

In [68]:
print(a)
for i in a:
    print(i) #prints rowwise

for i in a:
    for j in i:
        print(j, end=' ') #prints elementwise
print("\n")

for i in np.nditer(a):
    print(i, end=' ') #prints elementwise

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 4 5 6 7 8 9 10 11 

0 1 2 3 4 5 6 7 8 9 10 11 

In [ ]:
a, a.transpose(), a.T, a.ravel(), c.ravel() #ravels() converts any nd array to 1d

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26]))

## Stacking and splitting

In [70]:
a.T, b 

(array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [71]:
np.hstack((a.T,b,b,a.T,b)), np.vstack((a.T,b))

(array([[ 0,  4,  8, 12, 13, 14, 12, 13, 14,  0,  4,  8, 12, 13, 14],
        [ 1,  5,  9, 15, 16, 17, 15, 16, 17,  1,  5,  9, 15, 16, 17],
        [ 2,  6, 10, 18, 19, 20, 18, 19, 20,  2,  6, 10, 18, 19, 20],
        [ 3,  7, 11, 21, 22, 23, 21, 22, 23,  3,  7, 11, 21, 22, 23]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [72]:
a,b, np.hsplit(a, 2), np.vsplit(b,4)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 [array([[0, 1],
         [4, 5],
         [8, 9]]),
  array([[ 2,  3],
         [ 6,  7],
         [10, 11]])],
 [array([[12, 13, 14]]),
  array([[15, 16, 17]]),
  array([[18, 19, 20]]),
  array([[21, 22, 23]])])

In [73]:
#Fancy indexing

a, a[[1,2]],a[:, [1,2]]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]))

In [74]:
# Boolean indexing

a = np.random.randint(1,100,24).reshape(4,6)
a, a > 50

(array([[31, 52, 67, 75, 43, 56],
        [34, 94, 12, 88, 40, 10],
        [58,  6, 17, 53, 50, 68],
        [57, 55, 68, 13,  7, 21]]),
 array([[False,  True,  True,  True, False,  True],
        [False,  True, False,  True, False, False],
        [ True, False, False,  True, False,  True],
        [ True,  True,  True, False, False, False]]))

In [75]:
# Boolean masking
a[a > 50], a[a%2==0], a[(a>50) & (a%2==0)], a[~(a % 2 == 0)]

(array([52, 67, 75, 56, 94, 88, 58, 53, 68, 57, 55, 68]),
 array([52, 56, 34, 94, 12, 88, 40, 10, 58,  6, 50, 68, 68]),
 array([52, 56, 94, 88, 58, 68, 68]),
 array([31, 67, 75, 43, 17, 53, 57, 55, 13,  7, 21]))

## Broadcasting

In [77]:
a,b

(array([[31, 52, 67, 75, 43, 56],
        [34, 94, 12, 88, 40, 10],
        [58,  6, 17, 53, 50, 68],
        [57, 55, 68, 13,  7, 21]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [78]:
a+b

ValueError: operands could not be broadcast together with shapes (4,6) (4,3) 

In [ ]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
a,b, a+b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2]]),
 array([[0, 2, 4],
        [3, 5, 7]]))

In [ ]:
# remove missing values
a = np.array([1,2,3,np.nan, 5])
a[~(np.isnan(a))]

array([1., 2., 3., 4.])