In [35]:
import numpy as np

a = np.array([1,2,3]) # vector
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # matrix
c = np.array([[[1,2],[3,4]],[[1,2],[3,4]],[[1,2],[3,4]]]) # tensor
a,b,c, a.shape, b.shape, c.shape, a.ndim, b.ndim, c.ndim

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[[1, 2],
         [3, 4]],
 
        [[1, 2],
         [3, 4]],
 
        [[1, 2],
         [3, 4]]]),
 (3,),
 (3, 3),
 (3, 2, 2),
 1,
 2,
 3)

In [36]:
a = np.array([1,2,3], dtype=float)
b = np.array([2,3,0,-1], dtype=bool)
a,b

(array([1., 2., 3.]), array([ True,  True, False,  True]))

In [37]:
a = np.zeros((2,3))
b = np.ones((3,4),dtype=int)
c = np.random.random((2,4))
a,b,c

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]),
 array([[0.32296037, 0.82881697, 0.15673671, 0.48679602],
        [0.7381321 , 0.26798945, 0.65323369, 0.75855587]]))

In [38]:
a = np.arange(1,10) #just like normal range() fn of python
b = np.arange(1,11,2) #start:stop:stepsize
a,b

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [39]:
a = np.arange(1,13).reshape((1,12)) #1*12=12
b = np.arange(1,13).reshape((4,3)) #4*3=12
c = np.arange(1,13).reshape((2,6)) #2*6=12
a,b,c

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]))

In [40]:
# copy and view
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base is arr)# true (view/reference)
print(arr.reshape(2, 4) is arr)#false (copy)

True
False


In [41]:
# requires a same size for reshape
# np.arange(1,13).reshape((2,5)) #ValueError since 2*5 not equals 12

In [42]:
a = np.linspace(1,10,15) #linspace(x,y,z) = linearly spaced z points from x to y (incld. y)
b = np.linspace(1,10,15, dtype=int) #linspace(x,y,z) = linearly spaced z points from x to y (incld. y)
c = np.identity(3) #identity matrix
a,b,c

(array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
         4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
         7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]),
 array([ 1,  1,  2,  2,  3,  4,  4,  5,  6,  6,  7,  8,  8,  9, 10]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [43]:
a = np.arange(20).reshape(2,2,5)
print(a.ndim) #3d
print(a)
print(a.itemsize) #int taking 1 byte on my machine

b = np.ones((2,3),dtype=bool)
print(b.itemsize) #bool taking 1 byte on my machine

c = np.ones((2,3),dtype=float)
print(c.itemsize) #float taking 8 bytes on my machine

d = np.ones((2,3),dtype=np.int32)
print(d.itemsize) #4 bytes (4*8=32 bits) of int 

print(a.dtype, b.dtype, c.dtype, d.dtype)

3
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
8
1
8
4
int64 bool float64 int32


In [44]:
a = np.arange(8)
a = a.astype(np.int16)
a.itemsize

2

### Array operations

In [45]:
a = np.arange(12,24).reshape(3,4)
b = np.arange(12).reshape(3,4)

#scalar and arithmetic opn
2*a, a//2, a/2, a**0.5


(array([[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]),
 array([[ 6,  6,  7,  7],
        [ 8,  8,  9,  9],
        [10, 10, 11, 11]]),
 array([[ 6. ,  6.5,  7. ,  7.5],
        [ 8. ,  8.5,  9. ,  9.5],
        [10. , 10.5, 11. , 11.5]]),
 array([[3.46410162, 3.60555128, 3.74165739, 3.87298335],
        [4.        , 4.12310563, 4.24264069, 4.35889894],
        [4.47213595, 4.58257569, 4.69041576, 4.79583152]]))

In [46]:
#relational opn
a>20, b < 4, (a%4)==(b%2)

(array([[False, False, False, False],
        [False, False, False, False],
        [False,  True,  True,  True]]),
 array([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]]),
 array([[ True,  True, False, False],
        [ True,  True, False, False],
        [ True,  True, False, False]]))

In [47]:
#arithmetic opn
a+b, a-b, a*b #its not matrix multiplication

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 array([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]),
 array([[  0,  13,  28,  45],
        [ 64,  85, 108, 133],
        [160, 189, 220, 253]]))

### Arrays functions

In [48]:
a = np.random.random((3,3))
a = np.round(a*100)
a

array([[56., 68., 46.],
       [ 0., 79., 20.],
       [ 2., 51., 15.]])

In [49]:
# max/min/sum/prod
np.sum(a),np.max(a),np.min(a), np.prod(a)

(np.float64(337.0), np.float64(79.0), np.float64(0.0), np.float64(0.0))

In [50]:
# 1:row 0:col
np.max(a,axis=1), np.sum(a,axis=0)

(array([68., 79., 51.]), array([ 58., 198.,  81.]))

In [51]:
# mean/median/std/var
np.mean(a), np.mean(a, axis=0), np.median(a), np.std(a), np.var(a)

(np.float64(37.44444444444444),
 array([19.33333333, 66.        , 27.        ]),
 np.float64(46.0),
 np.float64(27.341913739048703),
 np.float64(747.5802469135803))

In [52]:
#trigno
np.sin(a)

array([[-0.521551  , -0.89792768,  0.90178835],
       [ 0.        , -0.44411267,  0.91294525],
       [ 0.90929743,  0.67022918,  0.65028784]])

In [53]:
# dot product/matrix multiplication
a = np.arange(12).reshape((3,4))
b = np.arange(12,24).reshape((4,3))

a.dot(b), np.dot(a,b), b.dot(a), np.dot(b,a)

(array([[114, 120, 126],
        [378, 400, 422],
        [642, 680, 718]]),
 array([[114, 120, 126],
        [378, 400, 422],
        [642, 680, 718]]),
 array([[164, 203, 242, 281],
        [200, 248, 296, 344],
        [236, 293, 350, 407],
        [272, 338, 404, 470]]),
 array([[164, 203, 242, 281],
        [200, 248, 296, 344],
        [236, 293, 350, 407],
        [272, 338, 404, 470]]))

In [54]:
#log and e
np.log(a), np.exp(a)

/tmp/ipykernel_18380/2288147719.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a), np.exp(a)


(array([[      -inf, 0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947, 1.94591015],
        [2.07944154, 2.19722458, 2.30258509, 2.39789527]]),
 array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
        [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]]))

## Indexing and slicing

In [ ]:
a, a[0], a[2][1], a[-1][-1], a[:,3], a[1:,1:3]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([0, 1, 2, 3]),
 np.int64(9),
 np.int64(11),
 array([ 3,  7, 11]),
 array([[ 5,  6],
        [ 9, 10]]))

In [77]:
print(a[::2, ::3]) #fetch only corner elemnts
a[::2, 1::2], a[::2, ::-1], a[::-1, ::-1]

[[ 0  3]
 [ 8 11]]


(array([[ 1,  3],
        [ 9, 11]]),
 array([[ 3,  2,  1,  0],
        [11, 10,  9,  8]]),
 array([[11, 10,  9,  8],
        [ 7,  6,  5,  4],
        [ 3,  2,  1,  0]]))

In [91]:
c = np.arange(27).reshape(3,3,3)
c, c[::2][::, ::, 1], c[::2][::, 1::, 1::], c[:,1:2, 1:2], c[::2, 0, ::2]

(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([[ 1,  4,  7],
        [19, 22, 25]]),
 array([[[ 4,  5],
         [ 7,  8]],
 
        [[22, 23],
         [25, 26]]]),
 array([[[ 4]],
 
        [[13]],
 
        [[22]]]),
 array([[ 0,  2],
        [18, 20]]))

In [95]:
for i in a:
    print(i) #prints rowwise

for i in a:
    for j in i:
        print(j, end=' ') #prints elementwise

for i in np.nditer(a):
    print(i, end=' ') #prints elementwise

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 4 5 6 7 8 9 10 11 0 1 2 3 4 5 6 7 8 9 10 11 

In [ ]:
a.transpose(), a.T, a.ravel(), c.ravel() #r::avels() converts any nd array to 1d

(array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26]))

## Stacking and splitting

In [102]:
a.T, b 

(array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [ ]:
np.hstack((a.T,b,b,a.T,b)), np.vstack((a.T,b))

(array([[ 0,  4,  8, 12, 13, 14, 12, 13, 14,  0,  4,  8, 12, 13, 14],
        [ 1,  5,  9, 15, 16, 17, 15, 16, 17,  1,  5,  9, 15, 16, 17],
        [ 2,  6, 10, 18, 19, 20, 18, 19, 20,  2,  6, 10, 18, 19, 20],
        [ 3,  7, 11, 21, 22, 23, 21, 22, 23,  3,  7, 11, 21, 22, 23]]),
 array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [112]:
a,b, np.hsplit(a, 2), np.vsplit(b,4)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 [array([[0, 1],
         [4, 5],
         [8, 9]]),
  array([[ 2,  3],
         [ 6,  7],
         [10, 11]])],
 [array([[12, 13, 14]]),
  array([[15, 16, 17]]),
  array([[18, 19, 20]]),
  array([[21, 22, 23]])])

In [119]:
#Fancy indexing

a, a[[1,2]],a[:, [1,2]]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]))

In [ ]:
# Boolean indexing

a = np.random.randint(1,100,24).reshape(4,6)
a, a > 50

array([[63,  4, 77, 93, 22, 63],
       [35, 84, 46, 77, 82, 76],
       [ 2,  1, 30, 31,  8,  1],
       [ 5, 17, 47, 36, 17, 62]])

In [128]:
# Boolean masking
a[a > 50], a[a%2==0], a[(a>50) & (a%2==0)], a[~(a % 2 == 0)]

(array([63, 77, 93, 63, 84, 77, 82, 76, 62]),
 array([ 4, 22, 84, 46, 82, 76,  2, 30,  8, 36, 62]),
 array([84, 82, 76, 62]),
 array([63, 77, 93, 63, 35, 77,  1, 31,  1,  5, 17, 47, 17]))

## Broadcasting

In [ ]:
a,b, a+b

(array([[63,  4, 77, 93, 22, 63],
        [35, 84, 46, 77, 82, 76],
        [ 2,  1, 30, 31,  8,  1],
        [ 5, 17, 47, 36, 17, 62]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]))

In [132]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
a,b, a+b

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 1, 2]]),
 array([[0, 2, 4],
        [3, 5, 7]]))